### ISSUE TITLE
Documentation for E2E testing

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#184]
We have started adding E2E tests. We should add documentation for the following:

- How to run E2E tests with a headless browser (`npm run cypress:run` after starting the E2E test docker env with `./docker/bin/e2e-env-up.sh` or using your dev env).
- How to run tests with the cypress app (`npm run cypress:open`).
- How E2E are organized.
- Add links to best practices.

cc @da2ce7

**Comment by da2ce7** [comment]
Hello @josecelano sounds good. However I would like to separate your proposal into two sections:

**Repository Documentation:**

- How E2E are organized.

**Blog Posts:**

-   How to run E2E tests with a headless browser (npm run cypress:run after starting the E2E test docker env with ./docker/bin/e2e-env-up.sh or using your dev env).
-   How to run tests with the cypress app (npm run cypress:open).
-   Add links to best practices.

These are more one-off kind of things, that are quite generic for more than just the repository. Hence I think that they should be considered for blog posts.  (We should still link to these blog posts in our readme or otherwise in our repo-docs).

**Comment by josecelano** [comment]
> Hello @josecelano sounds good. However I would like to seperate your proposal into two sections:
> 
> **Repository Documentation:**
> 
> * How E2E are organized.
> 
> **Blog Posts:**
> 
> * How to run E2E tests with a headless browser (npm run cypress:run after starting the E2E test docker env with ./docker/bin/e2e-env-up.sh or using your dev env).
> * How to run tests with the cypress app (npm run cypress:open).
> * Add links to best practices.
> 
> These are more one-off kind of things, that are quire generic for more than just the repository. Hence I think that they should be considered for blog posts. (We should still link to these blog posts in our readme or otherwise in our repo-docs).

Hi @ da2ce7, yes, it's a good idea. I think this [PR](https://github.com/torrust/torrust-index-frontend/pull/187) covers the **Repository Documentation**, and I have added the proposal for the new blog posts [here](https://github.com/torrust/torrust-website/discussions/42#discussioncomment-6550096).
