### ISSUE TITLE
The downloaded torrent filename is the torrent title instead of the original torrent file name

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#205]
If you upload a new torrent file with the name `mandelbrot_2048x2048.png.torrent` and then you download it by clicking on the download button:

![image](https://github.com/torrust/torrust-index-backend/assets/58816/662c7fa3-89e6-4d12-821c-8a9acf8c8cb8)

The file name will be: `mandelbrot.torrent` when you save it on disk. It does not use the original torrent name included in the `content-disposition` header.

![image](https://github.com/torrust/torrust-index-backend/assets/58816/facf1751-271f-46ec-a051-4c7a86f7b5c9)

The record in the database:

![image](https://github.com/torrust/torrust-index-backend/assets/58816/757ac91c-77f0-462e-989a-830af65ee531)

It's using the torrent title. I think it's a frontend issue because the backend adds the `content-disposition` header with the `filename`. 

It seems there are different ways and priorities to define the filename:

![image](https://github.com/torrust/torrust-index-backend/assets/58816/1de3b11f-8343-43c2-85bd-e021e0ba38b7)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

**Comment by mario-nt** [comment]
The downloaded torrent file's name is the same as the torrent tittle because the torrent tittle is passed to the function that executes the download, instead of the original torrent file's name.

In the screenshot below the torrent title is passed to the download function alongside the hash id in the **helpers.ts** file:

![image](https://github.com/torrust/torrust-index-frontend/assets/141633147/d5dda5e8-bdea-4dc2-8b01-a8881231e03e)

If we modify that value manually or check the debugger we can see how that torrent title is used to name the file that will be downloaded:

![image](https://github.com/torrust/torrust-index-frontend/assets/141633147/63715ba4-8968-48fb-983e-94211d5d9268)

![image](https://github.com/torrust/torrust-index-frontend/assets/141633147/b4eca9c8-12e9-4fcf-8cfb-e264f0e80833)

![image](https://github.com/torrust/torrust-index-frontend/assets/141633147/be92218d-0fb2-4947-860a-c016014b4424)

**Comment by mario-nt** [comment]
I'm working on fixing it by either retrieving the torrent's name from the database and setting the download attribute with that data or using the content-disposition header to get the same data.
