### ISSUE TITLE
Opinion: Table layout should be default layout.

### ISSUE THREAD

**Issue by hungfnt** [torrust/torrust-index-gui#542]
Or even further, the table layout should be the only layout.

In the table layout, we can easily compare column values across rows.

We can still have an expandable description, or I suggest showing the description when hovering over an item.

I made a poll [here](https://github.com/torrust/torrust-index-gui/discussions/545).

**Comment by josecelano** [comment]
Hi @ngthhu, thank you for the feedback.

In general, I tend to use the default one, but probably because I'm always just testing with a few torrents. I'm a newbie in BitTorrent. I have known it since the beginning, but I have not used it a lot (I've been mostly coding), so I can't give my opinion either as a designer or a user. I always encourage people to give us this type of feedback.

I would:

- Move this issue to a discussion (like a [poll](https://github.com/torrust/torrust-index-gui/discussions/categories/polls)).
- Add an option in the user profile so the user can decide which one is the default (when we have a user profile page. We needed to [allow the users to change their passwords](https://github.com/torrust/torrust-index-gui/issues/468)).

Maybe the reason to use the other one (I'm just guessing) was @mickvandijke wanted to give the project a more modern layout. I suppose the table layout is more common for this type of site.

A designer is re-designing the [Torrsut Website](https://torrust.com/). I will ask him.

**Comment by josecelano** [comment]
Hi @hungfnt we are going to use the user's settings: https://github.com/torrust/torrust-index-gui/issues/652
