### ISSUE TITLE
Config options for displaying file-sizes.

### ISSUE THREAD

**Issue by ghost** [torrust/torrust-index-gui#592]
Hey,
Would it be possible to change how file-sizes are displayed, or give a switch in the config so we can choose whether to display size in GB or GiB?
Downloading a torrent (e.g. https://index.torrust-demo.com/torrent/2b66980093bc11806fab50cb3cb41835b95a0362) which is indicated as being 659MB in size, is really 630MB on disc).

Always glad to see new commits and improvements to the project; looking forward to that long awaited 3.0.0 release.

**Comment by josecelano** [comment]
Hi @ty5e3a45 thank you for your feedback.

We could include both or add a config option. For the time being, I would prefer to include both because that depends on the user's preference. In the future, it could also be a user's settings, like dates, timezone, etc.

In my case (ubuntu), I see Megabyte in the "Files" app and Mebibyte in the terminal.

![image](https://github.com/user-attachments/assets/4f9ee5ed-180f-44a6-97a6-edfb956bb153)

![image](https://github.com/user-attachments/assets/62c49718-0d0e-4b0b-a7e8-4f6046ae3fa5)

659554304 bytes -> 0.6595543 Gigabyte
659554304 bytes -> 0.6142578 Gibibyte

659554304 bytes -> 659.5543 Megabyte (MB)
659554304 bytes -> 629      Mebibyte (MiB)

**Comment by josecelano** [comment]
Updated in the demo: https://index.torrust-demo.com/torrent/2b66980093bc11806fab50cb3cb41835b95a0362/debian-1250-amd64-netinstiso

![image](https://github.com/user-attachments/assets/6a136cf4-8ea5-4647-aa65-a8b5cdf686fc)

**Comment by ghost** [comment]
Appreciate the fix, thanks.
